version: "3"
services:

#  portainer:
#    container_name: portainer
#    image: portainer/portainer
#    restart: unless-stopped
#    ports: 
#      - 9000:9000


  # https://hub.docker.com/r/diginc/pi-hole/
  # https://github.com/pi-hole/docker-pi-hole
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    # 'dns:' is replaced by copying resolv.conf
    ports:
      - "53:53/tcp" # DNS
      - "53:53/udp" # DNS
#      - "67:67/udp" # DHCP
      - "80:80/tcp" # HTTP
      - "443:443/tcp" # HTTPS
    # https://github.com/pi-hole/docker-pi-hole#environment-variables
    environment:
      TZ: 'Europe/Rome'

    # Volumes store your data between container upgrades
    volumes:
      - './etc-resolv.conf:/etc/resolv.conf'
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
